module.exports = {
  goingHome: [ //array of events per 16th-note;
    ["kick", "hiHat"], //instruments to play on first sixteenth note
    ["hiHat"],
    ["hiHat"],
    ["hiHat"],
    ["kick", "snare", "hiHat"],
    ["hiHat"],
    ["hiHat"],
    ["hiHat"],
    ["kick", "hiHat"],
    ["hiHat"],
    ["hiHat"],
    ["hiHat"],
    ["kick", "snare", "hiHat"],
    ["hiHat"],
    ["hiHat"],
    ["hiHat"]
  ],
  heartless: [
    ["kick", "ride"],
    ["ride"],
    ["kick", "ride"],
    ["ride"],
    ["snare", "ride"],
    ["snare", "ride"],
    ["ride"],
    ["snare", "ride"],
    ["kick", "ride"],
    ["ride"],
    ["kick", "ride"],
    ["ride"],
    ["snare", "ride"],
    ["ride"],
    ["ride"],
    ["ride"]
  ],
  bass: [
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"],
    ["kick"]
  ],
  snare: [
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"],
    ["snare"]
  ]
};
